# Generated by Django 5.2.7 on 2026-08-26 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_technician_signup_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='related_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.servicerequest'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='related_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.technician_signup'),
        ),
        migrations.CreateModel(
            name='TechnicianRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_ratings', to='core.customer_signup')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_rating', to='core.servicerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.technician_signup')),
            ],
            options={
                'db_table': 'TechnicianRating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_points', models.IntegerField(default=1, help_text='Penalty point applied to rating. Must be 1 per business rule.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVERTED', 'Reverted')], default='ACTIVE', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('support_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warning', to='core.supportticket')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='core.technician_signup')),
            ],
            options={
                'db_table': 'TechnicianWarning',
                'ordering': ['-created_at'],
            },
        ),
    ]
