# Generated by Django 5.2.7 on 2026-08-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('incentive_type', models.CharField(choices=[('COMPLETED_JOBS_DAILY', 'Completed Jobs Daily'), ('FIVE_STAR_RATINGS', 'Five-Star Ratings')], max_length=50)),
                ('threshold', models.IntegerField(help_text='Number of jobs, ratings, etc. required to earn this incentive')),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Incentive',
            },
        ),
        migrations.CreateModel(
            name='TechnicianWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_incentive_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.technician_signup')),
            ],
            options={
                'db_table': 'TechnicianWallet',
            },
        ),
        migrations.CreateModel(
            name='TechnicianWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('JOB_EARNING', 'Job Earning'), ('INCENTIVE', 'Incentive'), ('WITHDRAWAL', 'Withdrawal'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, help_text='ID of related ServiceRequest, Incentive, or Withdrawal', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.technicianwallet')),
            ],
            options={
                'db_table': 'TechnicianWalletTransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.technician_signup')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='core.technicianwallettransaction')),
            ],
            options={
                'db_table': 'WithdrawalRequest',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianIncentiveAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifying_reference', models.CharField(help_text="e.g., '2026-08-30' or '5_star_milestone_1' to prevent duplicates", max_length=100)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.incentive')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_awards', to='core.technician_signup')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_award', to='core.technicianwallettransaction')),
            ],
            options={
                'db_table': 'TechnicianIncentiveAward',
                'unique_together': {('technician', 'incentive', 'qualifying_reference')},
            },
        ),
    ]
